class MyFile {
  String title;
  String oromicTitle;
  List<String> details;
  MyFile({this.title, this.oromicTitle, this.details});
}

class ListOfFiles {
  List<MyFile> listOfFiles = [];
  ListOfFiles() {
    listOfFiles.add(MyFile(
        title: '\nGreetings\nNagaa wal gaafachuu\n',
        oromicTitle: 'Nagaa wal gaafachuu',
        details: [
          'Hello\n Hayyee',
          'Good morning \n Akkam bulte?',
          'Good afternoon \n Akkam oolte?',
          'Good night \n Galgala gaarii',
          'How are you? \n Akkam ati?',
          'I\’m fine, Thank you \n Nagaakooti. Galatoomi',
          'Good \n Gaariidha',
          'Bad \n Gaarii miti/ Gadheedha',
          'Cool \nTasgabba’aa/Gaaridha',
          'I am not well \nHaala gaarii irra hin jiru',
          'What is your name? \n Maqaankee eenyu?',
          'My name is…\n Maqaankoo…',
          'And you? \nKankeehoo?/Atihoo?',
          'Nice to meet you \n Si arguukootti nan gammada',
          'It has been a long time \n Yeroon dheeraan darbeera/Tureera',
          'See you soon/see you later \n Booddee wal agarra',
          'Goodbye \n Nagaatti',
          'Take care \n Of eeggadhu',
          'Do you speak English? \nAfaan Ingiliffaa nii dubbattaa?',
          'I can speak a little English \n Ingliffa xiqqoo xiqqoo nan dubbadha',
          'I cannot speak English\n Ingliffa hin danda\’u',
          'Where are you from? \n Eessaa dhufte?',
          'I\’m from… \n Anii … irraan dhufe',
          'How old are you? \n Umuriinkee meeqa?',
          'I\’m … years old \n waggaankoo …',
          'It\’s the first time I have been here \n Yeroo jalqabaakoofin bakka kana jira'
        ]));

    listOfFiles.add(MyFile(
        title: '\nGeneral Conversation\nWaliin dubbii walii galaa\n',
        oromicTitle: 'Waliin dubbii\n walii galaa',
        details: [
          'Do you live here? \n Bakka kana jiraattaa?',
          'I\’m here on vacation \n Boqonnaa irran jira',
          'On business \n Hojii irran  jira',
          'For work  \n Hoojiidhaaf',
          'For studies \n Qo\’achuudhaaf',
          'What? \n Maal',
          'Who? \n Eenyuu',
          'Where? \n Eessa',
          'When? \n Yoom',
          'Why? \n Maalif',
          'Which one? \n Isa kam',
          'How? \n Akkamitti',
          'How many/How much? \n hammam?',
          'How much is this? \n Meeqa kuni',
          'How long? \n Hammamiif',
          'Is there/Are there? \n jiraa?',
          'What is this? \n kuni maali?',
          'What are you doing? \n Maal hojjetaa jirta?',
          'What do you want? \n Maal barbaadda?',
          'Yes \n Eyyee',
          'No \n Lakki',
          'Do you understand? \n Nii hubattaa?',
          'I do not understand \n hin hubadhu',
          'Thank you \n Galatoomi',
          'Sorry \n dhiifama',
          'Repeat please \n Dhiifama irra deebi\’i',
          'Can you repeat it? \n Irra deebi’uu dandeessaa?',
          'Speak more slowly \n Suuta jedhii dubbadhu',
          'I\’m sorry \n Nan gadda',
          'I\’m fine \n Nagaakooti',
          'I do not know \n Ani hin beeku',
          'I like it \n Nan jaalladha',
          'I do not like it \n Ani hin jaalladhu',
          'You are welcome \n Baga nagan dhuftan',
          'With pleasure \n Gammachuudhaan',
          'I want \n Nan fedha',
          'Where are we going? \n Eessa deema jirra?',
          'We\’re going to… \n …deemaa jirra',
          'I will \n Nan godha',
          'What happened now? \n Maaltu ta\’e amma?',
          'Do not forget \n Hin irraanfatin!',
          'Excuse me \n Dhiifama naa godhi',
          'Can I use your phone? \n Bilbilakee fayyadamuu nan dandaa\’a?',
          'What does this mean? \n Maal jechuudha kun?',
          'How do you pronounce this? \n kana akkamitti sagaleessita?',
          'That\’s right /Correct\n Sirriidha',
          'That\’s wrong \n Dogoggoradha',
          'No problem \n Rakkoon hin jiru',
          'Help \n Gargaarsa',
          'Just kidding \n qoosaan jira',
          'Before \n Dura',
          'After \n Booda',
          'Until \n Ammasitti',
          'Good luck \n Carraa gaarii'
        ]));

    listOfFiles.add(MyFile(
        title: '\nNumbers\nLakkoofsa\n',
        oromicTitle: 'Lakkoofsa',
        details: [
          'Zero \n Duwwaa',
          'One \n Tokko',
          'Two \n Lama',
          'Three \n Sadii',
          'Four \n Afur',
          'Five \n Shan',
          'Six \n Ja’a',
          'Seven \n Torba',
          'Eight \n Saddeet',
          'Nine \n Sagal',
          'Ten \n Kudhan',
          'Eleven \n Kudha tokko',
          'Twelve \n Kudha lama',
          'Thirteen \n Kudha sadii',
          'Fourteen \n Kudha afur',
          'Fifteen \n Kudha shan',
          'Sixteen \n Kudha ja’a',
          'Seventeen \n Kudha torba',
          'Eighteen \n Kudha saddeet',
          'Nineteen \n Kudha sagal',
          'Twenty \n Digdama',
          'Twenty one  \n Digdamii tokko',
          'Twent two \n Digdamii lama',
          'Twenty-three \n Digdamii sadii',
          'Twenty-four \n Digdamii afur',
          'Twenty-five \n Digdamii shan',
          'Twenty-six \n Digdamii ja’a',
          'Twenty-seven \n Digdamii torba',
          'Twenty-eight \n Digdamii saddeet',
          'Twenty-nine \n Digdamii sagal',
          'Thirty \n Soddoma',
          'Forty \n Afurtama',
          'Fifty \n Shantama',
          'Sixty\nJaatama',
          'Seventy\nTorbaatama',
          'Eighty\n Saddeettama',
          'Ninety\nSagaltama',
          'Hundred\nDhibba tokko',
          'Thousand\nKuma tokko',
          'Ten thousand\n Kuma kudhan',
          'One hundred-thousand\nKuma dhibba tokko',
          'One million\n Miliyoona tokko',
          'First \n Tokkoffaa',
          'Second \n Lammaffaa',
          'Third \n Sadaffaa',
          'Fourth \n Afuraffaa',
          'Fifth\n Shanaffaa',
          'Sixth\nja’affaa',
          'Seventh\n Torbaffaa',
          'Eighth \n Saddeettaffaa',
          'Nineth\nSalgaffaa',
          'Tenth\nKudhanaffaa',
        ]));

    listOfFiles.add(
        MyFile(title: '\nColors\nHalluu \n', oromicTitle: 'Halluu', details: [
      'Red\nDiimaa',
      'Blue \n Cuquuliisa',
      'Green\n Magariisa',
      'Yellow\n Keelloo',
      'Orange\n Birtukaanii',
      'Pink\n Diiminee',
      'Purple \n Dhiilgee',
      'Brown\n Magaala/Daammii',
      'Black \n Gurraacha',
      'White\n Adii',
      'Gray\n Daalacha/Odolcha',
    ]));
    listOfFiles.add(MyFile(
        title: '\nDirections and places\nKallattii fi bakka\n ',
        oromicTitle: 'Kallattii fi bakka',
        details: [
          'Here\n Asi',
          'There\nAchi',
          'North \n Kaaba',
          'South\n Kibba',
          'East\n Baha',
          'West\n Dhiha',
          'Up\n Ol',
          'Down\n Gadi',
          'Left\nBitaa',
          'Right\nMirgaa',
          'Turn left\n Gara bitaa gori',
          'Turn right \n Gara mirgaa gori',
          'Behind\n Booda',
          'Above/On\n Irra keessa/Irra',
          'Under\n Jala',
          'Opposite \n Faallaa',
          'Far \n Fagoo',
          'Near\n Dhihoo',
          'Corner\n Roga',
          'Cross the Street\n Daandii qaxxaamuri',
          'Crossing \n qaxxaamuruu',
          'Bridge \n riqicha',
          'Where is it? Eessa jira?',
          'Is it far? \n Fagoodhaa?',
          'How do I get there? \n Akkamittin achii dhaquu dandaa’a?',
          'Airport\n Buufata Xiyyaaraa',
          'Bus station\n Buufata Konkolaataa',
          'Home\n mana',
          'Hospital \n Hospitaala',
          'School\n Mana Barumsaa'
        ]));
    listOfFiles.add(
        MyFile(title: '\nMeals\nNyaata\n ', oromicTitle: 'Nyaata', details: [
      'Breakfast\nCiree',
      'Lunch \n Laaqana',
      'Dinner \n Irbaata',
      'I\’m hungry \n Beela\’aan jira',
      'I\’m full \n Quufeen jira',
      'Drink \n Dhuguu',
      'Eat \n Nyaachuu',
      'Knife\n Aaduu',
      'Spoon \n fal\’aana',
      'Glass \n Xaasaa',
      'Tea\n sha\’ee',
      'Coffee \n Buna',
      'Cold \n qorra',
      'Delicious\n Minyaa\’aa',
      'Taste \nDhamdhama',
      'Sweet \n Mi\’ooftuu',
      'Salty\n Ashaba\’aa',
      'Bitter \n Hadhooftuu',
      'Food \n Nyaata',
      'Meat \n Foon',
      'Beef \n Foon Hoolaa',
      'Chicken \n Foon indaanqoo',
      'Egg \n Hanqaaquu/Killee',
      'Lamb\n Hoolaa',
      'Fish \n Qurxummii',
      'Vegetables\nKuduraaf Muduraa',
      'Butter\n Dhadhaa',
      'Bread\n Buddeen',
      'Rice \n Ruuzii',
      'Salt \n Ashaboo',
      'Vinegar \n Komxaaxxee',
      'Herbs \n Aramaa',
      'Garlic \n Qullubbii adii',
      'Onion \n Qullubbii diimaa',
      'Ginger\n Jinjibila',
      'Water \n Bishaan',
      'Milk \n Aannan',
      'Alcoholic drinks \n Dhugaatii alkoolii',
      'Banana \n Muuzii',
      'Papaya \n Paappayyaa',
      'Mango \n Mangoo',
      'Is there a menu? \n Menu/Baafati jiraa?',
      'I\’m drunk \n Machaa\’een jira',
      'I like this food \n Nyaata kana nan jaalladha',
      'What is this called? \n maqaan kanaa maali?',
      'Peanut\n Ocholonii',
      'I do not eat meat \n Foon hin nyaadhu',
      'I do not eat eggs \n Hanqaaquu hin nyaadhu'
    ]));

    listOfFiles.add(MyFile(
        title: '\nShopping \nBittaa fi gurgurtaa\n',
        oromicTitle: 'Bittaa fi gurgurtaa',
        details: [
          'Money \n Qarshii/Maallaqa',
          'Price \n Gatii',
          'Expensive \n Mi\’aa/Qaalii',
          'Cheap\n Rakasa',
          'Pay\n Kaffaluu',
          'Change\nJijjiirraa',
          'How much is it? \n meeqa gatiin kanaa?',
          'Can you write the price? \nGatiisaa barreessuu dandeessaa?',
          'Can you give it cheaper? \n Gatii hir\’isuu nii dandeessaa?',
          'Can I exchange money here? \n Maallaqa sharafuu nan danda\’aa asitti?',
          'Where is the nearest mall? \n wiirtuun daldalaa dhiyoon eessa?',
          'Where can I pay? \n Eessattin kaffaluu dandaa’a?',
          'I\’ll think about it \n Ittin yaada',
          'I do not want it \n Hin barbaadu',
          'It\’s very cheap \n Baayyee rakasa',
          'I will take this one \n Isa kanan fudhadha',
          'It\’s expensive \n Mi\’aadha/Qaalidha',
          'Can I try it? \n Yaaluu nan danda\’aa?',
          'Do you have other colors? \n Halluu kan biraan jiraa?',
          'Do you have bigger sizes? \n Kanarra kan guddatu jiraa?',
          'Do you have smaller sizes? \n Kanarra kan xiqqaatu jiraa?',
          'Small \n Xiqqoo',
          'Medium? \n Giddu galeessa',
          'Large \n  Guddaa',
          'Extra-large \n Baayyee guddaa',
          'Too short \n Baayyee gabaabaa',
          'Too large \n Baayyee guddaa',
          'Belt \n Qabattoo/Saqqii',
          'Dress \n Uffata',
          'Shoes \n Kophee',
          'Socks \n Kaalsii',
          'Pants \n Paantii',
          'Cotton \n Jirbii',
          'Camera \n Kaameraa',
          'Computer \n kompiyuteera',
          'Car \n Makinaa',
        ]));
    listOfFiles.add(MyFile(
        title: '\nDating\nBeellama\n',
        oromicTitle: 'Beellama',
        details: [
          'Do you mind if I sit here? \n Bakka kana taa’uu nan danda\’aa?',
          'Can I invite you something to drink? \n Waan dhugamu maal siif ha dhufu?',
          'Are you single? \n Jaalallee qabdaa?',
          'I\’m single \n Jaalallee hin qabu',
          'Are you married? \n Gaa\’ila dhaabbatteettaa?',
          'I\’m married? \n Gaa\’ila dhaabbadheera',
          'Do you have a girlfriend? \n Hiriyaa duubaraa qabdaa?',
          'Do you have a boyfriend? \n Hiriyaa dhiira qabdaa?',
          'Would you like to watch movies? \n Fiilmii ilaaluu nii jaallattaa?',
          'Are you free tomorrow? \n boor boqonnaa qabdaa?',
          'I\’m free tomorrow \n Boor boqonnaan qaba',
          'Will I see you again? \n Deebinee wal arguu nii dandeenyaa?',
          'When will we be able to see each other again? \n Yoom deebinee wal arguu dandeenya?',
          'Can I call you? \nSiif bilbiluu nan danda’aa?',
          'You are very kind \n Ati nama gaaridha',
          'You are beautiful \n Ati baayyee bareedduudha',
          'I love you \n Sin jaalladha',
          'Will you marry me? \n Na fuutaa?/ Natti nii heerumtaa?',
          'I have a girlfriend\n Hiriyaa duubaraan qaba',
          'I\’m with my boyfriend \n Hiriyaa dhiiraakoo wajjiniin jira',
          'Stop calling me \n Na waamu dhiisi'
        ]));
    listOfFiles.add(
        MyFile(title: '\nFamily\nMaatii\n', oromicTitle: 'Maatii', details: [
      'How many peoples are there in your family? \n Maatii keessan keessa nama meeqatu jira?',
      'Do you have…? \n … qabdaa?',
      'He/she is my…. \n Inni/Isheen …. Kooti',
      'Brother \n Obboleessa',
      'Sister \n Obboleettii',
      'Older brother \n Obboleessa hangafaa',
      'Younger brother \n Obboleessa quxisuu',
      'Older sister \n Obboleetti hangafaa',
      'Younger sister \n Obboleetti quxisuu',
      'Mother/Mom \n Haadha/Aayyoo',
      'Father/Dad \n Abbaa',
      'Son \n Ilma',
      'Daughter \n Intala/durba',
      'Grandmother\n Akkoo',
      'Grandfather\n Akaakaa',
      'Uncle \n Eessuma',
      'Aunt \n Adaadaa',
      'Nephew/Cousin \n Durbii',
      'Husband\n Abbaa manaa/ Dhirsa',
      'Wife \n Haadha manaa',
      'Friend \n Hiriyaa',
      'Relatives \n Fira',
      'Stepfather\n Abbaa buddeenii',
      'Stepmother\nHaadha buddeenii',
      'Fiance \n Kadhimaa'
    ]));
    listOfFiles.add(MyFile(
        title: '\nFeeling sick\nDhukkubbiin namatti dhaga\'aamuu\n',
        oromicTitle: 'Dhukkubbiin namatti dhaga\'aamuu',
        details: [
          'I do not feel well \n Keessikoo nagaa miti',
          'I\’m sick \n Na dhukkubaa jira',
          'Headache\n Mataa bowuu',
          'Stomachache \n Garaa ciniinnaa',
          'Back pain \n Dhukkubbii dugdaa',
          'Asthma \n Asmii',
          'Cough \n Qufaa',
          'Constipation \n Gogiinsa garaa',
          'Diarrhea \n Garaa kaasaa',
          'Fever \n Hoo\’ina qaamaa',
          'Influenza \n Infilu\’eenzaa',
          'Throat pain \n Dhukkubbii qoonqoo',
          'Something has made me feel bad \n Waanti tokko na arseera',
          'Medicine \n Qoricha',
          'I have a fever/I have a temperature\n  Qaama na guba',
          'Vomit \n Ol deebisuu/ Balaqqamuu',
          'I\’m dizzy \n Na joonjeessa/Of na wallaalchisa',
          'I am worse \n Natti hammaatee jira',
          'I\’m better \n Natti fooyya\’ee jira',
          'It hurts here \n bakka kana na dhukkuba',
          'I cannot sleep \n Rafuu hin danda\’u',
          'I ran out of medicine \n Qorichi na jala dhume',
          'This is my usual medication \n Kuni qorichan deddeebi\’ee fayyadamuudha',
          'I need a doctor who speaks English \n Ogeessa Ingiliffa haasa\’uun barbaada',
          'I have been vaccinated \n Talaallii fudhadheen ture',
          'Ambulance \n Ambuulaansii',
          'Clinic \n Kilinika',
          'Surgeon \n Ogeessa baqaqsanii yaaluu',
          'Blood pressure \n Dhiibbaa dhiigaa',
          'Operation/Surgery \n Baqaqsanii yaaluu',
          'I think it’s broken \n Cabuun isaa hin oolle',
          'Antibiotics \n Aantiibaayootikii',
        ]));
    listOfFiles.add(MyFile(
        title: '\nBody parts\nKutaalee qaamaa\n',
        oromicTitle: 'Kutaalee qaamaa',
        details: [
          'Head \n Mataa',
          'Hair \n Rifeensa',
          'Face \n Fuula',
          'Forehead \n Adda',
          'Brain\n Sammuu',
          'Chin \n Areeda',
          'Cheek \n Maddii',
          'Eyebrow\n Nyaara',
          'Eyelid \n Baallee ijaa',
          'Eye \n Ija',
          'Nose \n Funyaan',
          'Lip \n Hidhii',
          'Mouth\n Afaan',
          'Ear \n Gurra',
          'Shoulder \n zaggoo/Gatiittii',
          'Neck \n Morma',
          'Tongue \n Arraba',
          'Chest \n Qoma',
          'Breast \n Harma',
          'Abdomen \n Garaa',
          'Navel \n Handhuura',
          'Penis\n Qunxurroo',
          'Vagina \n Buqqushaa',
          'Hand \n Harka',
          'Finger\n Quba',
          'Arm \n Ciqilee',
          'Waist \n Mudhii',
          'Back \n Dugda',
          'Thigh\n Sarbaa',
          'Knee \n Jilba',
          'Ankle \n Gulubii',
          'Leg\n Miilla',
          'Bone\n Lafee',
          'Heart\n Onnee',
          'Liver \n Tiruu',
          'Skin \n Gogaa',
          'Throat \n Qoonqoo',
          'Tooth/Teeth\n Ilkaan',
        ]));
    listOfFiles.add(MyFile(
        title: '\nParts of the day\nKutaalee guyyaa \n',
        oromicTitle: 'Kutaalee guyyaa',
        details: [
          'Dawn/ Early morning \n Obboroo/Barii',
          'Sunrise\nBaha Biiftuu',
          'Morning \n Ganama/Waare dura',
          'Midday \n walakkeessa guyyaa',
          'Afternoon\nWaaree booda',
          'Evening\n Galgala',
          'Sunset\n Lixa Biiftuu',
          'Midnight\n Halkan walakkaa',
          'Yesterday \n Kaleessa',
          'Tomorrow \nBoor'
        ]));
    listOfFiles.add(MyFile(
        title: '\nDays of the week\nGuyyoota torbanii \n',
        oromicTitle: 'Guyyoota torbanii',
        details: [
          'Day\n Guyyaa',
          'Week \n Torban',
          'Monday \n Wiixata',
          'Tuesday\n Kibxata',
          'Wednesday\n Roobii',
          'Thursday\n Kamisa',
          'Friday\n Jimaata',
          'Saturday \n Sanbata',
          'Sunday \n Dilbata'
        ]));
    listOfFiles.add(MyFile(
        title: '\nMonths of the year\nJi\'oota waggaa\n',
        oromicTitle: 'Ji\'oota waggaa',
        details: [
          'Month \n Ji’a/Baatii',
          'Year \n Wagga',
          'January \n Amajji',
          'February\n Guraandhala',
          'March \n Bitootessa',
          'April \n Eebla',
          'May \n Caamsaa',
          'June \n Waxabajji',
          'July \n Adoolessa',
          'August \n  Hagayya',
          'September \n Fulbaana',
          'October \n Onkoloolessa',
          'November \n Sadaasa',
          'December \n Mudde'
        ]));
    listOfFiles.add(MyFile(
        title: '\nTime\nSa\'a/Yeroo\n',
        oromicTitle: 'Sa\'a/Yeroo',
        details: [
          'What time is it? \n Yeroon/ Sa\’a meeqa?',
          'It\’s one o’clock \n Sa\’a tokko',
          'It\’s  two o\’clock \n Sa\’a lama',
          'It\’s eight o\’clock \n Sa\’a saddeet',
          'It\’s five past one \n Tokkoo fi shan',
          'It\’s twenty past eleven \n Kudha tokkoo fi digdama',
          'It\’s five to one \n Tokko shan hir\’uu',
          'It\’s half past one \n Tokkoo fi walakkaa',
          'It\’s quarter past one \n Tokkoo fi ruubii',
          'It\’s quarter to one \n Tokko ruubii hir\’uu',
          'It\’s two in the morning \n Ganama keessa sa\’a lama',
          'See you at one o\’clock \n Sa\’a tokkotti wal agarra',
          'The bank opens at three \n Baankiin sa\’a sadiitti banama',
        ]));
    listOfFiles.add(MyFile(
        title: '\n50 most common verbs\nGochoota bebbeekamoo 50\n',
        oromicTitle: 'Gochoota bebbeekamoo 50',
        details: [
          'Have/has \n Qabaachuu',
          'Do \n Dalaguu/Hojjechuu',
          'Can \n Danda’uu',
          'Speak \n Dubbachuu',
          'Say \n Jechuu',
          'Go \n Deemuu',
          'Give \n kennuu',
          'See \n Ilaaluu',
          'Know \n Beekuu',
          'Believe \n Amanuu',
          'Want \n Fedhuu',
          'Love/like \n Jaallachuu',
          'Eat \n Nyaachuu',
          'Drink \n Dhuguu',
          'Sleep \n Rafuu',
          'Listen \n Dhaggeeffachuu',
          'Hear \n Dhaga’uu',
          'Write \n Barreessuu',
          'Sit \n Taa’uu',
          'Stand \n Dhaabbachuu',
          'Push \n Dhiibuu',
          'Pull \n Harkisuu',
          'Wash \n Miicuu',
          'Take \n Fudhachuu',
          'Hurt \n Miidhuu',
          'Break \n Cabsuu',
          'Come \n Dhufuu',
          'Buy \n Bituu',
          'Sell \n Gurguruu',
          'Begin \n Jalqabuu',
          'Finish \n Fixuu/Xumuruu',
          'Get \n Argachuu',
          'Kill \n Ajjeesuu',
          'Kiss \n Dhungachuu',
          'Steal \n Hatuu',
          'Build \n Ijaaruu',
          'Open \n Banuu',
          'Close \n Cufuu',
          'Clean \n Qulqulleessuu',
          'Teach \n Barsiisuu',
          'Learn \n Barachuu',
          'Cry\n Boo’uu',
          'Laugh \n Kolfuu',
          'Drive \n Oofuu/Konkolaachisuu',
          'Call \n Waamuu',
          'Praise \n Faarsuu',
          'Loose\n Dhabuu/Mo’amuu',
          'Win \n Mo’uu',
          'Prepare \n Qopheessuu',
          'Change \n Jijjiiruu'
        ]));
    listOfFiles.add(MyFile(
        title: '\n40 most common adjectives\nIbsa maqaa  bebbeekamoo 40\n',
        oromicTitle: 'Ibsa maqaa  bebbeekamoo 40',
        details: [
          'Pretty \n Bareedduu',
          'Ugly \n Fokkisaa',
          'Happy \n Gammachuu',
          'Sad \n Gadda',
          'Tall \n Dheeraa',
          'Short \n Gabaabaa',
          'Big\n Guddaa',
          'Small \n Xiqqoo',
          'Difficult \n Cimaa',
          'Poor \n Hiyyeessa',
          'Delicious \n Mi\’ooftuu',
          'Boring\n Jibbisiisaa',
          'New \n Haaraa',
          'Old \n Moofaa',
          'Cold \n diilalla\’aa/Qorraa',
          'Hot \n Ho’aa',
          'Red \n Diimaa',
          'Black \n Gurraacha',
          'White \n Adii',
          'Simple \n Salphaa',
          'Expensive \n Qaalii/Mi\’aa',
          'Cheap \n Rakasa',
          'Fast \n Ariifataa',
          'Slow \n Suuta jedhaa',
          'Awake \n Dammaquu',
          'Asleep \n Rafuu',
          'Crazy \n Maraatuu',
          'Strong \n Cimaa',
          'Weak \n Dadhabaa',
          'Sick \n Dhukkubsataa',
          'Healthy \n Fayyaalessa',
          'Complicated \n Wal xaxaa',
          'Good \n Gaarii',
          'Bad \n Gadhee',
          'Clean \n Qulqulluu',
          'Dirty \n Xura’aa',
          'Wet \n Jiidhaa',
          'Dry \n Gogaa',
          'Empty \n Duwwaa',
          'Full \n Guutuu'
        ]));
  }
  List<MyFile> get getListOfMyFiles => listOfFiles;
}
